Table Users {
    id serial [pk]
    username varchar [unique]
    email varchar
}

Table post {
    id serial [pk]
    user_id int
    title varchar
    body text
    created_at timestamp
}

Ref

Table profile {
    id serial [pk]
    username varchar
    description varchar
    
}

Ref 

"La relacion entre el nombre y el perfil, 
llave primaria que identificaria a la persona
y el id que vendria siendo el perfil, cada perfil se identifica por su username y el post se guarda con su username cómo llave foránea al buscar el post sabes a qué usuario pertenece sin necesidad de tener el id"